Problem Statement 1: Write a Python program to multiply a 𝑀 × 𝑁 matrix by 𝑁 × 𝐴 matrix and
create a real matrix product.

In [ ]:
m = int(input ("Enter a number:"))
n = int(input ("Enter a number:"))
a = int(input ("Enter a number:"))

import numpy as np


Matrix1= np.random.uniform(0,1, size=(m,n))
Matrix2 = np.random.uniform(0,1, size=(n,a))
print("First Matrix:")
print(Matrix1)
print("Second Matrix:")
print(Matrix2)
result = np.dot(Matrix1, Matrix2)
print("Dot product of two arrays:")
print(result)

Enter a number:5
Enter a number:3
Enter a number:2
First Matrix:
[[0.85993516 0.25609084 0.00119217]
 [0.42314663 0.69742245 0.51779734]
 [0.23272236 0.63643256 0.29311776]
 [0.09252556 0.09207653 0.37395902]
 [0.58010896 0.86072809 0.32763676]]
Second Matrix:
[[0.96851833 0.53710672]
 [0.35091615 0.71768245]
 [0.75639188 0.37136814]]
Dot product of two arrays:
[[0.92363112 0.64611159]
 [1.04621978 0.92009619]
 [0.67044222 0.69060782]
 [0.40478341 0.25465427]
 [1.11171134 1.05098373]]
